sudo: false
dist: trusty
language: ruby
rvm:
- 2.2.3
- jruby-9
- rbx-3
matrix:
  allow_failures:
  - rvm: rbx-3
cache: bundler
bundler_args: --without debug
script:
- bundle exec rspec --format d
- >
  if [[ "$(rvm current)" = "ruby-"* ]]; then
    bundle exec rubocop
  fi
- >
  if [[ "$(rvm current)" = "ruby-"* ]]; then
    bundle exec codeclimate-test-reporter
  fi
env:
  global:
  - TRAVIS=1 CI=1 COVERAGE=1
  # google translate api key:
  - secure: "LSP0PfgTfRfyjm3iV770tgqF+G1G4lD+s7LSFE7QwsX+HoZPm8SwHW9S0sOThub+qAkOkfPvApvHwL8nBBFPPM+ZZcgBUViLfErUSOKHFLQt6/pMQvpRg+47hSUszedGnxHck6z9q71a/4GrxHcuY+VslCpT+PhCTt0rsAf3bvY="
