sudo: true
dist: trusty
language: ruby
rvm:
- 2.2.3
- jruby
- rbx
matrix:
  allow_failures:
  - rvm: rbx
cache: bundler
bundler_args: --without debug
script:
- bundle exec rspec --format d
- bundle exec rubocop
- bundle exec codeclimate-test-reporter
env:
  global:
  - TRAVIS=1 CI=1 COVERAGE=1
  # google translate api key:
  - secure: "LSP0PfgTfRfyjm3iV770tgqF+G1G4lD+s7LSFE7QwsX+HoZPm8SwHW9S0sOThub+qAkOkfPvApvHwL8nBBFPPM+ZZcgBUViLfErUSOKHFLQt6/pMQvpRg+47hSUszedGnxHck6z9q71a/4GrxHcuY+VslCpT+PhCTt0rsAf3bvY="
  # codeclimate repo token:
  - secure: Qz5xzCujPHN5jGZYiCcsZ73BN5DzJTQwDMuj0kJ+W2nBzGQuQDvADT0rHFsHOhdQ/epZe89pVL8wEbr5GaCZ+iZCt1JfasZpvyvCtwMUkPtjrLxpWwVKlH3u7xqAzyYj7Z8ru0VqHni19d6DPzAaNGyV3gaiI1pR6Y63Ux+msM0=
