os: linux
dist: focal
language: ruby
rvm:
- 3.0.0
- 2.7.0
- 2.6.5
- 2.5.7
- jruby-9.2.14.0
cache: bundler
bundler_args: --without debug
before_install:
- gem update --system && gem install bundler -v '~>2.0' --no-document
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- bundle exec rspec --format d
- >
  if [[ "$(rvm current)" = "ruby-2.7"* ]]; then
    bundle exec rubocop
  fi
after_script:
- >
  if [[ "$(rvm current)" = "ruby-2.7"* ]]; then
    ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  fi
env:
  global:
  - TRAVIS=1 CI=1 COVERAGE=1
  # google translate api key:
  - secure: "LSP0PfgTfRfyjm3iV770tgqF+G1G4lD+s7LSFE7QwsX+HoZPm8SwHW9S0sOThub+qAkOkfPvApvHwL8nBBFPPM+ZZcgBUViLfErUSOKHFLQt6/pMQvpRg+47hSUszedGnxHck6z9q71a/4GrxHcuY+VslCpT+PhCTt0rsAf3bvY="
